#!/bin/bash/

# This process must be repeated separately for each of the chromosomes and running the process for all the chromosome at once using a for loop will not be possible since 
# the no. of blocks of each chromosome is different and the no. of blocks must be correctly mentioned as it is not possible to provide file names that are not available 
# in the directory.

# Directory containing the VCF files
vcf_directory="/Bulk/Path\ to\ Output\ Directory/chr1/"
output_directory="/Cohorts/path/to/output/directory"
tag="bcftools_concat"
instance_type="mem1_ssd1_v2_x16"

# First check the no. of blocks of VCF for each chromosome and replace the no. in the curly brackets accordingly
vcf_files=("$vcf_directory"ukb24310_c1_b{1..12448}_v1.vcf.gz)

# Construct the bcftools command
bcftools_cmd="bcftools concat *.vcf.gz -Oz -o SAS_WGS_concat_c1.vcf.gz"

# Construct the dx command with multiple -iin arguments
dx_command="dx run swiss-army-knife"

for vcf_file in "${vcf_files[@]}"; do
  dx_command+=" -iin=\"$vcf_file\""
done

# Add the remaining flags and the bcftools command
dx_command+=" -icmd=\"$bcftools_cmd\" --tag=\"$tag\" --instance-type=\"$instance_type\" --destination=\"$output_directory\""

# Print the dx command for debugging purposes
echo "Running command: $dx_command"

# Execute the dx command
eval $dx_command

# Print confirmation message
echo "Input Files Loaded. VCF merge initiated"
